let fakeArray = Array.from({ length: 100 }, (_, i) => i + 1);

let numbersPares = fakeArray.filter((number) => {
  return number % 2 === 0;
});

console.log(numbersPares[0]);
console.log(numbersPares[1]);
console.log(numbersPares[2]);
console.log(numbersPares[3]);
console.log(numbersPares[4]);
console.log(numbersPares[5]);
console.log(numbersPares[6]);
console.log(numbersPares[7]);
console.log(numbersPares[8]);
console.log(numbersPares[9]);
console.log(numbersPares[10]);
console.log(numbersPares[11]);
console.log(numbersPares[12]);
console.log(numbersPares[13]);
console.log(numbersPares[14]);
console.log(numbersPares[15]);
console.log(numbersPares[16]);
console.log(numbersPares[17]);
console.log(numbersPares[18]);
console.log(numbersPares[19]);
console.log(numbersPares[20]);
console.log(numbersPares[21]);
console.log(numbersPares[22]);
console.log(numbersPares[23]);
console.log(numbersPares[24]);
console.log(numbersPares[25]);
console.log(numbersPares[26]);
console.log(numbersPares[27]);
console.log(numbersPares[28]);
console.log(numbersPares[29]);
console.log(numbersPares[30]);
console.log(numbersPares[31]);
console.log(numbersPares[32]);
console.log(numbersPares[33]);
console.log(numbersPares[34]);
console.log(numbersPares[35]);
console.log(numbersPares[36]);
console.log(numbersPares[37]);
console.log(numbersPares[38]);
console.log(numbersPares[39]);
console.log(numbersPares[40]);
console.log(numbersPares[41]);
console.log(numbersPares[42]);
console.log(numbersPares[43]);
console.log(numbersPares[44]);
console.log(numbersPares[45]);
console.log(numbersPares[46]);
console.log(numbersPares[47]);
console.log(numbersPares[48]);
console.log(numbersPares[49]);
